services:
  ignition-gateway:
    image: inductiveautomation/ignition:8.1.45
    ports:
      - 18088:8088
      - 18000:8000
    volumes:
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      GATEWAY_ADMIN_PASSWORD: password
      IGNITION_EDITION: standard
      ACCEPT_IGNITION_EULA: Y
    command: > 
      -n ignition-mod-dev
      -r /restore.gwbk
      -d
      --
      -Dignition.allowunsignedmodules=true
      -Dia.developer.moduleupload=true